### ISSUE TITLE
Crash in template selector

### ISSUE THREAD

**Issue by simonpoole** [simonpoole/OpeningHoursFragment#31]
Rotating the device while in the template selector will crash vespucci (not the test app) with 

> java.lang.IllegalStateException: Fragment OpeningHoursFragment{2120f77} not attached to a context.
> at android.support.v4.app.Fragment.requireContext(Fragment.java:614)
> at android.support.v4.app.Fragment.getResources(Fragment.java:678)
> at ch.poole.openinghoursfragment.OpeningHoursFragment.valueToEntry(OpeningHoursFragment.java:3315)

in the call to getResources().

**Comment by simonpoole** [comment]
Crash fixed in https://github.com/simonpoole/OpeningHoursFragment/commit/cbf2828a86cd09cc2ef8d073843b017581646c6f
